### ISSUE TITLE
Error when compiling qt port

### ISSUE THREAD

**Issue by Marc34** [Yabause/yabause#134]
Hi

I try to compile qt port, exactly as usual, but here is the error that happens on Linux Mint and Manjaro, although all is exactly as before  :

/yabause-master/yabause/src/qt/ui/UIYabause.cpp: Dans la fonction membre ‘void UIYabause::on_aFileSettings_triggered()’:
/yabause-master/yabause/src/qt/ui/UIYabause.cpp:707:43: erreur: ‘FALSE’ was not declared in this scope
     VIDSoftSetVdp1ThreadEnable(num == 1 ? FALSE : TRUE);
                                           ^
/yabause-master/yabause/src/qt/ui/UIYabause.cpp:707:51: erreur: ‘TRUE’ was not declared in this scope
     VIDSoftSetVdp1ThreadEnable(num == 1 ? FALSE : TRUE);
                                                   ^
/yabause-master/yabause/src/qt/ui/UIYabause.cpp:713:32: erreur: ‘FALSE’ was not declared in this scope
     VIDSoftSetVdp1ThreadEnable(FALSE);
                                ^
qt/CMakeFiles/yabause-qt.dir/build.make:449 : la recette pour la cible « qt/CMakeFiles/yabause-qt.dir/ui/UIYabause.cpp.o » a échouée
make[2]: *** [qt/CMakeFiles/yabause-qt.dir/ui/UIYabause.cpp.o] Erreur 1
CMakeFiles/Makefile2:159 : la recette pour la cible « qt/CMakeFiles/yabause-qt.dir/all » a échouée
make[1]: *** [qt/CMakeFiles/yabause-qt.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Compiling gtk works.

Thank for your help.

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/Yabause/yabause/commit/9123d7fda00f2b44f29e105e0d40a1d70dcab66e

**Comment by Marc34** [comment]
Thank for your help, but the problem is still here.

/yabause-master/yabause/src/qt/ui/UIYabause.cpp: In member function ‘void UIYabause::appendLog(const char*)’:
/yabause-master/yabause/src/qt/ui/UIYabause.cpp:318:15: warning: format not a string literal and no format arguments [-Wformat-security]
   qWarning( s );
               ^
/yabause-master/yabause/src/qt/ui/UIYabause.cpp: In member function ‘void UIYabause::on_aFileSettings_triggered()’:
/yabause-master/yabause/src/qt/ui/UIYabause.cpp:713:32: error: ‘FALSE’ was not declared in this scope
     VIDSoftSetVdp1ThreadEnable(FALSE);
                                ^
make[2]: *** [src/qt/CMakeFiles/yabause-qt.dir/ui/UIYabause.cpp.o] Erreur 1
make[1]: *** [src/qt/CMakeFiles/yabause-qt.dir/all] Erreur 2
make: *** [all] Erreur 2

**Comment by cyberwarriorx** [comment]
Sorry, should be fixed now
